server:
  port: 8081


spring:
  jpa:
    hibernate:
      ddl-auto: none
    database: mysql
    show-sql: true
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test_jpa?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false&serverTimezone=UTC
